@ContosoPizza_HostAddress = http://localhost:5288

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Chicken Bacon Ranch",
    "isGlutenFree": false
}

###

PUT {{ContosoPizza_HostAddress}}/pizza/6
Content-Type: application/json

{
    "id": 6,
    "name": "Chicken Bacon Ranch",
    "isGlutenFree": true
}

###

DELETE {{ContosoPizza_HostAddress}}/pizza/7

###